[theme]

# Primary accent for interactive elements
primaryColor = '#F63366'

# Background color for the main content area
backgroundColor = '#F3CFC6'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#E5E4E2'

# Color used for almost all text
textColor = '#000000'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"
